"""Corpus typed-edge backfill (edge_backfill.py).

Synthetic fixtures in temp stores prove the backfill's contract: it derives
the same typed edges the write path would, additively (existing edges stay
byte-identical), idempotently (a second run inserts nothing), with a precise
one-DELETE rollback, and dry-run writes nothing. All node ULIDs are freshly
generated by the temp stores and appear nowhere in the mining artifact.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from living_memory.edge_backfill import (
    BACKFILL_BASIS,
    backfill_edges,
    run_backfill,
)
from living_memory.edge_derivation import (
    CONTENT_CORRECTION_KIND,
    CONTENT_REFERENCE_KIND,
    DERIVED_FROM_KIND,
    FAILURE_RESOLUTION_KIND,
    SAME_COMMIT_BASIS,
    SHARED_FILES_BASIS,
)
from living_memory.models import Connection, Node
from living_memory.retrieval import _traversal
from living_memory.storage import MemoryStore

SCOPE = "project:edge-backfill-tests"


def _store(tmp_path: Path) -> MemoryStore:
    return MemoryStore(tmp_path / "memory.sqlite3")


def _remember(store: MemoryStore, content: str, **context: Any) -> Node:
    context.setdefault("scope", SCOPE)
    return store.append_trace(content, context)


def _edge_rows(store: MemoryStore) -> list[tuple[Any, ...]]:
    """Full connection rows as plain tuples for byte-identity comparison."""

    return [
        tuple(row)
        for row in store.connection.execute(
            "SELECT id, source_id, target_id, type, weight, metadata, "
            "created_at, updated_at FROM connections ORDER BY id"
        ).fetchall()
    ]


def _only(store: MemoryStore, **kwargs: Any) -> Connection:
    edges = store.list_connections(**kwargs)
    assert len(edges) == 1, f"expected one edge, got {len(edges)}"
    return edges[0]


def _seed_typed_material(store: MemoryStore) -> dict[str, Node]:
    """Seed traces that fire R1c, R6, R4a, R4b, and R2a."""

    stale = _remember(store, "The runner lock lives in /tmp/runner.lock")
    correction = _remember(
        store, f"CORRECTION to trace {stale.id}: the lock lives in /var/lock, NOT /tmp"
    )
    referrer = _remember(store, "Background job internals note")
    referee_note = _remember(
        store, f"Re-run building on {referrer.id} finished cleanly today."
    )
    commit_a = _remember(store, "Implementation of the widget", commit="abc1234def0")
    commit_b = _remember(store, "Verification of the widget change", commit="abc1234def0")
    file_a = _remember(store, "Design note for the loader", files=["src/loader.py"])
    file_b = _remember(store, "Bugfix in the loader", files=["src/loader.py"])
    problem = _remember(
        store,
        "Dead pid left node_status stuck",
        type="root_cause",
        task="recover-node",
        timestamp="2026-06-01T10:00:00Z",
    )
    fix = _remember(
        store,
        "Recover interrupted tree node status by clearing the pid",
        type="fix",
        task="recover-node",
        timestamp="2026-06-01T10:02:00Z",
    )
    return {
        "stale": stale,
        "correction": correction,
        "referrer": referrer,
        "referee_note": referee_note,
        "commit_a": commit_a,
        "commit_b": commit_b,
        "file_a": file_a,
        "file_b": file_b,
        "problem": problem,
        "fix": fix,
    }


# --- correctness: each go-rule produces a marked, correctly-typed edge --------


def test_backfill_derives_all_go_rules_with_marker(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        nodes = _seed_typed_material(store)
        report = backfill_edges(store, apply=True)

        # R1c: correction supersedes the named stale node.
        r1c = _only(
            store,
            source_id=nodes["correction"].id,
            target_id=nodes["stale"].id,
            relation_type="supersedes",
        )
        assert r1c.weight == 0.9
        assert r1c.metadata["rule"] == "R1c"
        assert r1c.metadata["kind"] == CONTENT_CORRECTION_KIND
        assert r1c.metadata["basis"] == BACKFILL_BASIS

        # R6: plain citation -> directed related, kind preserved for traversal.
        r6 = _only(
            store,
            source_id=nodes["referee_note"].id,
            target_id=nodes["referrer"].id,
            relation_type="related",
        )
        assert r6.metadata["kind"] == CONTENT_REFERENCE_KIND
        assert r6.metadata["basis"] == BACKFILL_BASIS

        # R4a: same commit -> undirected related, rule basis preserved.
        src, tgt = sorted((nodes["commit_a"].id, nodes["commit_b"].id))
        r4a = _only(store, source_id=src, target_id=tgt, relation_type="related")
        assert r4a.metadata["basis"] == BACKFILL_BASIS
        assert r4a.metadata["rule_basis"] == SAME_COMMIT_BASIS
        assert r4a.metadata["commit"] == "abc1234"

        # R4b: shared files -> undirected related.
        fsrc, ftgt = sorted((nodes["file_a"].id, nodes["file_b"].id))
        r4b = _only(store, source_id=fsrc, target_id=ftgt, relation_type="related")
        assert r4b.metadata["rule_basis"] == SHARED_FILES_BASIS
        assert r4b.metadata["files"] == ["src/loader.py"]

        # R2a: root cause caused the fix (direction problem -> fix).
        r2a = _only(
            store,
            source_id=nodes["problem"].id,
            target_id=nodes["fix"].id,
            relation_type="caused",
        )
        assert r2a.metadata["kind"] == FAILURE_RESOLUTION_KIND
        assert r2a.metadata["basis"] == BACKFILL_BASIS

        by_rule = report["rules"]
        assert by_rule["R1c"]["new"] == 1
        assert by_rule["R2a"]["new"] == 1
        assert by_rule["R4a"]["new"] == 1
        assert by_rule["R4b"]["new"] == 1
        assert by_rule["R6"]["new"] == 1
        assert report["totals"]["new_rows"] == 5


def test_backfill_marker_never_touches_kind_so_traversal_holds(tmp_path: Path) -> None:
    """The rollback marker rides in `basis`; the `kind` retrieval reads survives."""

    with _store(tmp_path) as store:
        referrer = _remember(store, "Original design decision")
        citer = _remember(store, f"Plan extends {referrer.id} with the new curve.")
        backfill_edges(store, apply=True)

        edge = _only(
            store,
            source_id=citer.id,
            target_id=referrer.id,
            relation_type="related",
        )
        # forward referrer->referee 0.75, backward 0.9 (retrieval._traversal).
        forward = _traversal(edge, citer.id, causal_mode=False)
        backward = _traversal(edge, referrer.id, causal_mode=False)
        assert forward is not None and round(forward[1], 6) == round(edge.weight * 0.75, 6)
        assert backward is not None and round(backward[1], 6) == round(edge.weight * 0.9, 6)


# --- idempotency --------------------------------------------------------------


def test_backfill_idempotent_second_run_zero_new(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        _seed_typed_material(store)
        first = backfill_edges(store, apply=True)
        assert first["totals"]["new_rows"] > 0
        after_first = _edge_rows(store)

        second = backfill_edges(store, apply=True)
        assert second["totals"]["new_rows"] == 0
        assert _edge_rows(store) == after_first


# --- additive guarantee: existing edges byte-identical ------------------------


def test_backfill_leaves_existing_edges_byte_identical(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        nodes = _seed_typed_material(store)
        # An unrelated hand edge, and one that collides with a rule's output.
        unrelated = store.create_connection(
            nodes["referrer"].id,
            nodes["stale"].id,
            "related",
            weight=0.42,
            metadata={"kind": "manual"},
        )
        colliding = store.create_connection(
            nodes["correction"].id,
            nodes["stale"].id,
            "supersedes",
            weight=0.3,
            metadata={"kind": "manual"},
        )
        before = {row[0]: row for row in _edge_rows(store)}

        report = backfill_edges(store, apply=True)
        assert report["totals"]["new_rows"] > 0
        after = {row[0]: row for row in _edge_rows(store)}

        # Every pre-existing row is unchanged, including the colliding one:
        # the R1c supersedes edge was skipped, not reweighted to 0.9.
        for edge_id, row in before.items():
            assert after[edge_id] == row
        assert after[colliding.id][4] == 0.3  # weight untouched
        assert '"manual"' in after[colliding.id][5]  # metadata untouched
        assert unrelated.id in after


# --- dry-run writes nothing ---------------------------------------------------


def test_dry_run_writes_nothing_but_reports_plan(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        _seed_typed_material(store)
        before = _edge_rows(store)

        report = backfill_edges(store, apply=False)

        assert report["mode"] == "dry-run"
        assert report["applied"] is False
        assert report["totals"]["new_rows"] > 0  # it *would* have inserted
        assert report["typed_share"]["after"]["projected"] is True
        assert _edge_rows(store) == before  # ... but wrote nothing


def test_run_backfill_dry_run_default_via_path(tmp_path: Path) -> None:
    db_path = tmp_path / "memory.sqlite3"
    with MemoryStore(db_path) as store:
        _seed_typed_material(store)
        before = _edge_rows(store)

    report = run_backfill(db_path)  # apply defaults to False
    assert report["applied"] is False

    with MemoryStore(db_path) as store:
        assert _edge_rows(store) == before


# --- precise rollback ---------------------------------------------------------


def test_rollback_deletes_exactly_backfilled_rows(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        _seed_typed_material(store)
        store.create_connection(
            _remember(store, "hub").id,
            _remember(store, "spoke").id,
            "related",
            weight=0.5,
            metadata={"kind": "manual"},
        )
        before = _edge_rows(store)

        report = backfill_edges(store, apply=True)
        assert report["totals"]["new_rows"] > 0
        rollback_sql = report["rollback"]
        assert BACKFILL_BASIS in rollback_sql

        with store.connection:
            store.connection.execute(rollback_sql)

        assert _edge_rows(store) == before


# --- R5a annotation (opt-in) --------------------------------------------------


def _seed_schema_with_source_edge(store: MemoryStore) -> tuple[Node, Node, Connection]:
    trace = _remember(store, "Concrete instance of the acceptance-repair procedure")
    schema = store.create_node(
        level="schema",
        content="Procedure: acceptance-repair\n1. reproduce\n2. fix",
        context={"scope": SCOPE, "procedure_id": "acceptance-repair"},
        provenance={"source_traces": [trace.id]},
    )
    # Pre-existing schema->trace related edge without the annotation, as an
    # older consolidation pass left it.
    edge = store.create_connection(
        schema.id, trace.id, "related", weight=0.6, metadata={"basis": "procedural"}
    )
    return schema, trace, edge


def test_r5a_annotation_is_additive_and_off_by_default(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        _schema, _trace, edge = _seed_schema_with_source_edge(store)
        before = {row[0]: row for row in _edge_rows(store)}

        # Default: R5a disabled -> the schema edge stays byte-identical.
        default_report = backfill_edges(store, apply=True)
        assert default_report["totals"]["r5a_annotations"] == 0
        assert {row[0]: row for row in _edge_rows(store)}[edge.id] == before[edge.id]

        # Opt-in: annotate. Weight/type/id unchanged; only metadata gains keys.
        report = backfill_edges(store, apply=True, annotate_derived_from=True)
        assert report["totals"]["r5a_annotations"] == 1
        annotated = store.get_connection(edge.id)
        assert annotated is not None
        assert annotated.type == "related"
        assert annotated.weight == 0.6
        assert annotated.metadata["kind"] == DERIVED_FROM_KIND
        assert annotated.metadata["rule"] == "R5a"
        assert annotated.metadata["basis"] == "procedural"  # original kept

        # Idempotent: re-annotating finds nothing new.
        again = backfill_edges(store, apply=True, annotate_derived_from=True)
        assert again["totals"]["r5a_annotations"] == 0


def test_r5a_dry_run_writes_no_annotation(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        _schema, _trace, edge = _seed_schema_with_source_edge(store)
        before = _edge_rows(store)

        report = backfill_edges(store, apply=False, annotate_derived_from=True)
        assert report["totals"]["r5a_annotations"] == 1  # planned
        assert _edge_rows(store) == before  # but not written


# --- caps / exclusions carried from the shared rules --------------------------


def test_backfill_never_links_decayed_nodes(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        stale = _remember(store, "Old fact soon to decay")
        store.soft_delete_node(stale.id, "test decay")
        _remember(store, f"CORRECTION to trace {stale.id}: obsolete now")

        report = backfill_edges(store, apply=True)
        assert store.list_connections(target_id=stale.id) == []
        assert report["totals"]["new_rows"] == 0


def test_shared_files_fanout_cap_excludes_hub_files(tmp_path: Path) -> None:
    with _store(tmp_path) as store:
        # 21 traces citing one hub file -> fanout > 20 -> no R4b edges.
        for index in range(21):
            _remember(store, f"touch number {index}", files=["src/hub.py"])
        report = backfill_edges(store, apply=True)
        assert "R4b" not in report["rules"] or report["rules"]["R4b"]["new"] == 0
        assert store.list_connections() == []


def test_multi_rule_pair_collapses_to_one_row(tmp_path: Path) -> None:
    """A pair sharing both a commit and a file yields one related row."""

    with _store(tmp_path) as store:
        left = _remember(store, "left change", commit="deadbee1234", files=["src/x.py"])
        right = _remember(store, "right change", commit="deadbee1234", files=["src/x.py"])
        report = backfill_edges(store, apply=True)

        src, tgt = sorted((left.id, right.id))
        edges = store.list_connections(source_id=src, target_id=tgt, relation_type="related")
        assert len(edges) == 1  # collapsed, not two rows
        assert report["totals"]["multi_rule_rows"] >= 1
        # Both contributing rules are recorded in the sample metadata.
        merged = edges[0].metadata
        assert merged["rule_basis"] == SHARED_FILES_BASIS  # R4b applied last
        assert merged["commit"] == "deadbee"  # R4a key survives the merge
